### ISSUE TITLE
Upgrading Sentry.Protocol to 1.0.6 stops messages being sent to Sentry.io

### ISSUE THREAD

**Issue by Amadiere** [getsentry/sentry-dotnet-protocol#37]
I have a relatively simple application that broke for me when I upgraded the `Sentry.Protocol` library from 1.0.5 to 1.0.6. Reverting it back to 1.0.5 fixed the issue, and rolling it forward once again continued to break it.

When debugging, I can see an exception (e.g. a typo in the DB connection string) occur, it will then progress to the `OnException` method of my `SentryUnhandledExceptionLogger` and calls the `CaptureException()` method with no further warnings or errors. However - no messages appear in Sentry. Furthermore, using Fiddler, I do not see any network requests leaving my machine. As mentioned above, if I roll back to `1.0.5`, everything is fine again.

I'm running a .NET Framework 4.7.2 ASP.NET WebApi application.

The code is setup like so.
I have a `ExceptionFilterAttribute` defined as below:

``` csharp
public class SentryUnhandledExceptionLogger : ExceptionFilterAttribute
{
    public override void OnException(HttpActionExecutedContext context)
    {
        SentrySdk.CaptureException(context.Exception);
    }
}
````

I also have setup the following lines within the `Application_Start()` method inside the `Global.asax.cs` file:
``` csharp
SentryDatabaseLogging.UseBreadcrumbs();
_sentrySdk = SentrySdk.Init(o =>
{
    o.Dsn = new Dsn(ConfigurationManager.AppSettings["SentryDsn"]);
    o.Environment = ConfigurationManager.AppSettings["SentryEnvironment"] ?? "Unknown";
    o.AddEntityFramework();
});

GlobalConfiguration.Configure(WebApiConfig.Register);
// ----x snip x----
```
and further down in the same file, I define: 
``` csharp
protected void Application_Error()
{
    var exception = Server.GetLastError();
    SentrySdk.CaptureException(exception);
}

public override void Dispose()
{
    _sentrySdk?.Dispose();
    base.Dispose();
}
```

And finally, within the `WebApiConfig.cs`'s `Register()` method that's called within the `Application_Start()` above, I have the following line to define the filter:

``` csharp
config.Filters.Add(new SentryUnhandledExceptionLogger());
```

For completeness, the packages are:
``` xml
<package id="Sentry" version="1.1.2" targetFramework="net472" />
<package id="Sentry.EntityFramework" version="1.0.0" targetFramework="net472" />
<package id="Sentry.PlatformAbstractions" version="1.0.0" targetFramework="net472" />
<package id="Sentry.Protocol" version="1.0.6" targetFramework="net472" />
```

I've tried this on two different machines to similar affect - but each time mirroring the implementation somewhat.

Is this an issue that other people are having? Is it something that you guys are unable to reproduce? And if so, is there a favoured way you'd like (other than what I think is the code needed above) me of providing a failing example?

**Comment by bruno-garcia** [comment]
Your setup seems correct. And the fact 1.0.5 works properly is an indication of that.
Could you please provide a failing example? I'd be able to debug through and find the culprit.

**Comment by Amadiere** [comment]
I've stripped away everything I possibly could fine and left with a minimal ASP.NET WebApi project. I've done two commits, one with the initial version working with `Sentry.Protocol` version 1.0.5. I then did a second commit where all I did was upgrade to 1.0.6.

You can clone this on:  https://github.com/Amadiere/SentryProtocolSandbox 

Only notes are that the Web.Config contains the `DSN`, which I've left as "INSERT DSN HERE" to avoid putting secrets up. I _could_ probably trim the project down a bit more, but it's probably small enough.

Accessing **http://localhost:50034/api/sites** will trigger an exception.

**Comment by bruno-garcia** [comment]
@Amadiere Thanks for the repro. I found the issue and it's that 1.0.6 having moved an extension method to the base type is a breaking change to the previous Sentry package. 

Could you please update your dependency `Sentry` to package version `1.1.3-beta4` ? 
This version works properly with Protocol `1.0.6`. 

I'll get 1.1.3 out so the two latest stable are compatible.

**Comment by Amadiere** [comment]
I've just updated the NuGet package for `Sentry` to `1.1.3-beta4` and can confirm that exceptions are now being sent to Sentry.io as expected. Thanks for the good work and turnaround :)

**Comment by bruno-garcia** [comment]
Thank you again for reporting and specially the repro. 
Deploying Sentry version 1.2.0 right now.

**Comment by bruno-garcia** [comment]
@Amadiere https://www.nuget.org/packages/Sentry/1.2.0

**Comment by xt0rted** [comment]
@bruno-garcia there's a Roslyn analyzer that can help prevent breaking changes to public apis. An older version of this is in use in [microsoft/ApplicationInsights-dotnet](https://github.com/microsoft/ApplicationInsights-dotnet).

It creates a list of the public apis that you commit with the code and then on build it'll compare that to what's in the project and if they differ it can fail the build. That way you'll know how the versions need to be bumped.

- https://www.nuget.org/packages/Microsoft.CodeAnalysis.PublicApiAnalyzers/
- [Analyzer rules](https://github.com/dotnet/roslyn-analyzers/blob/master/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md)

**Comment by bruno-garcia** [comment]
Thanks @xt0rted ! I've created an issue for this here https://github.com/getsentry/sentry-dotnet/issues/204
